spring.application.name=fleetcore
spring.datasource.url=jdbc:postgresql://localhost:5433/fleetcore
spring.datasource.username=fleetcore
spring.datasource.password=fleetcore

spring.data.web.pageable.max-page-size=100
spring.data.web.pageable.default-page-size=20
